### ISSUE TITLE
APIs for form to create inventory item

### ISSUE THREAD

**Issue by tiffany-slac** [eed-web-application/core-inventory-system#10]
Create New Inventory Item API:
- Endpoint: POST /v1/inventory/items
- Request Payload: SLAC ID, serial, nickname, maker, model, revision, cue category, cater shop, & subsystem.

Retrieve Nicknames API:
- Endpoint: GET /v1/inventory/nicknames
- Response: List of available nicknames to populate the dropdown menu.

Retrieve Information based on Nickname API:
- Endpoint: GET /v1/inventory/nicknames/{nickname}
- Response: Details about the selected nickname (maker, model, revision, cue category). (ex data from depot is shown)

![DEPOTnicknames](https://github.com/eed-web-application/core-inventory-system/assets/149618362/e319a08e-cbfc-405f-a420-4df62e971113)

**Comment by bisegni** [comment]
this=>  `GET /v1/inventory/nicknames` i think is the api for the global search on the item, and the nickname in our scenario is the 'name'

**Comment by bisegni** [comment]
what are the 'Subsystems' ?

**Comment by tiffany-slac** [comment]
the user should be able to search for an item based on their nickname, but when they create an item, they'll also need to assign a nickname to that item. The nickname has its own data that's associated with it that will tell the user the item's maker name, model, revision, and cue category and autofill these details. I attached a screen recording of what the user sees when creating an item that may help.

https://github.com/eed-web-application/core-inventory-system/assets/149618362/75f0ee54-03af-4e5e-86ee-e5ec6c08ae06

**Comment by tiffany-slac** [comment]
The user will have the option of selecting the subsystem the item belongs to. The API will be populating the dropdown menu of the subsystem options:
<img width="687" alt="Screen Shot 2023-12-05 at 2 50 29 PM" src="https://github.com/eed-web-application/core-inventory-system/assets/149618362/c1e6a4d9-4898-4c09-b4bc-262d7e505924">

**Comment by bisegni** [comment]
yes what does they mean for subsystem? the building? some other categorization? because in this case we will use the tag for this...

**Comment by bisegni** [comment]
> the user should be able to search for an item based on their nickname, but when they create an item, they'll also need to assign a nickname to that item. The nickname has its own data that's associated with it that will tell the user the item's maker name, model, revision, and cue category and autofill these details. I attached a screen recording of what the user sees when creating an item that may help.
> 
>  Screen.Recording.2023-12-05.at.2.59.30.PM.mov

so if i understand, the create a depot base on a nickname, so a nickname is the specific element right? and the they can change the hardware the is stil named as it. i well understand this should be the our history. So we have an element that remain fixed in the name but will be associated with many hardware during the years

**Comment by tiffany-slac** [comment]
Subsystem seems to be a more specific category of a class, but after looking at it on depot, it doesn't seem like it's used or necessary. I will remove it from the form. 

As for nicknames, it is indeed a specific identifier used to refer to a particular device, serving as a shorthand for the Make/Model/Rev. The nickname remains fixed even if the physical hardware or specific models associated with it changes over time. I hope to get the information on the available nicknames, makes, model, and rev to display on the interface for the user to select when creating a device.

**Comment by bisegni** [comment]
ahok i suppose that, this is my 'History of the element' i still need to model it, but anyway i understand. Thanks
