### ISSUE TITLE
Create GET /inventory endpoint

### ISSUE THREAD

**Issue by tiffany-slac** [eed-web-application/core-inventory-system#9]
Create the GET /inventory endpoint that returns the following fields for all inventory items:

- SLAC ID
- Nickname
- Serial Number
- Location

If the query parameter search is present, then search through the inventory items returning only those found from the search.

**Comment by bisegni** [comment]
in the new inventory, all the information will be attribute, so generally when you retrieve an element you will fill a list of all attribute
